import {
  computeStats,
  filterByGender,
  filterData,
  sortData,
} from "../src/dataFunctions.js";
import { fakeData } from "./data.js";

//console.log(fakeData);

describe("filterData", () => {
  it("la data se filtra según el valor elegido por el usuario", () => {
    const dataResults = [
      {
        id: "ea660b10-85c4-4ae3-8a5f-41cea3648e3e",
        title: "Kiki's Delivery Service",
        description:
          "A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.",
        director: "Hayao Miyazaki",
        producer: "Hayao Miyazaki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/4/48/Kiki%27s_Delivery_Service_%282%29.jpg",
        release_date: "1989",
        rt_score: "96",
        people: [
          {
            id: "4151abc6-1a9e-4e6a-5678-aac05ra641js",
            name: "Kiki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/59/Kiki.jpg",
            gender: "Female",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Witch",
          },
          {
            id: "7151abc6-1a9e-4e6a-9711-ddb50ea572ec",
            name: "Jiji",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b4/Jiji.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Cat",
          },
          {
            id: "6574cfr2-9w3d-2x1h-8531-gge23iu489ko",
            name: "Ursula",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/12/Ursula.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "4321dse3-6r6s-3r4d-5641-rdq19re765de",
            name: "Tombo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/6f/Tombo.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
            name: "Osono",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3a/Osono.jpg",
            gender: "Female",
            age: "30",
            eye_color: "Brown",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
            name: "Fukuo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Fukuo.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "fb083a4e-77b2-4623-a2e0-6bbca5bfd5b2",
            name: "Ursula's Log Cabin",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b5/Ursula%27s_Log_Cabin.jpg",
            climate: "TODO",
            terrain: "TODO",
            surface_water: "40",
            residents: ["TODO"],
          },
          {
            id: "c57fb2cb-ea85-4d73-8808-cf5dcd28c22e",
            name: "Koriko",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/05/Koriko.jpg",
            climate: "Mild",
            terrain: "Hill",
            surface_water: "50",
            residents: ["TODO"],
          },
          {
            id: "62346d33-caa0-4c17-8016-0aca56f3066b",
            name: "Karikiya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e3/Majo002.jpg",
            climate: "Mild",
            terrain: "City",
            surface_water: "30",
            residents: ["TODO"],
          },
          {
            id: "64a996aa-481e-4627-9624-ab23f59a05a9",
            name: "Guchokipanya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Gutiokipanja.jpg",
            climate: "Continental",
            terrain: "Hill",
            surface_water: "50",
            residents: [
              {
                id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
                name: "Osono",
              },
              {
                id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
                name: "Fukuo",
              },
            ],
          },
        ],
        vehicles: [],
      },
    ];
    expect(filterData(fakeData, "director", "Hayao Miyazaki")).toEqual(
      dataResults
    );
  });
});

describe("filterByGender", () => {
  it("la data se filtra según el valor elegido por el usuario (Femenino)", () => {
    const dataResults = [
      {
        id: "ea660b10-85c4-4ae3-8a5f-41cea3648e3e",
        title: "Kiki's Delivery Service",
        description:
          "A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.",
        director: "Hayao Miyazaki",
        producer: "Hayao Miyazaki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/4/48/Kiki%27s_Delivery_Service_%282%29.jpg",
        release_date: "1989",
        rt_score: "96",
        people: [
          {
            id: "4151abc6-1a9e-4e6a-5678-aac05ra641js",
            name: "Kiki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/59/Kiki.jpg",
            gender: "Female",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Witch",
          },
          {
            id: "7151abc6-1a9e-4e6a-9711-ddb50ea572ec",
            name: "Jiji",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b4/Jiji.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Cat",
          },
          {
            id: "6574cfr2-9w3d-2x1h-8531-gge23iu489ko",
            name: "Ursula",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/12/Ursula.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "4321dse3-6r6s-3r4d-5641-rdq19re765de",
            name: "Tombo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/6f/Tombo.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
            name: "Osono",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3a/Osono.jpg",
            gender: "Female",
            age: "30",
            eye_color: "Brown",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
            name: "Fukuo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Fukuo.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "fb083a4e-77b2-4623-a2e0-6bbca5bfd5b2",
            name: "Ursula's Log Cabin",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b5/Ursula%27s_Log_Cabin.jpg",
            climate: "TODO",
            terrain: "TODO",
            surface_water: "40",
            residents: ["TODO"],
          },
          {
            id: "c57fb2cb-ea85-4d73-8808-cf5dcd28c22e",
            name: "Koriko",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/05/Koriko.jpg",
            climate: "Mild",
            terrain: "Hill",
            surface_water: "50",
            residents: ["TODO"],
          },
          {
            id: "62346d33-caa0-4c17-8016-0aca56f3066b",
            name: "Karikiya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e3/Majo002.jpg",
            climate: "Mild",
            terrain: "City",
            surface_water: "30",
            residents: ["TODO"],
          },
          {
            id: "64a996aa-481e-4627-9624-ab23f59a05a9",
            name: "Guchokipanya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Gutiokipanja.jpg",
            climate: "Continental",
            terrain: "Hill",
            surface_water: "50",
            residents: [
              {
                id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
                name: "Osono",
              },
              {
                id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
                name: "Fukuo",
              },
            ],
          },
        ],
        vehicles: [],
      },
      {
        id: "ff24da26-a969-4f0e-ba1e-a122ead6c6e3",
        title: "Whisper of the Heart",
        description:
          "Shizuku lives a simple life, dominated by her love for stories and writing. One day she notices that all the library books she has have been previously checked out by the same person: 'Seiji Amasawa'. Curious as to who he is, Shizuku meets a boy her age whom she finds infuriating, but discovers to her shock that he is her 'Prince of Books'. As she grows closer to him, she realises that he merely read all those books to bring himself closer to her. The boy Seiji aspires to be a violin maker in Italy, and it is his dreams that make Shizuku realise that she has no clear path for her life. Knowing that her strength lies in writing, she tests her talents by writing a story about Baron, a cat statuette belonging to Seiji's grandfather.",
        director: "Yoshifumi Kondō",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/7/7b/Whisper_of_the_Heart.jpg",
        release_date: "1995",
        rt_score: "91",
        people: [
          {
            id: "42a69bf6-b5e8-42b1-b05a-12c3d05e7c1e",
            name: "Shizuku Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/67/Shizuku_Tsukishima.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Light black",
            specie: "Human",
          },
          {
            id: "fc196c4f-0201-4ed2-9add-c6403f7c4d32",
            name: "Baron Humbert von Gikkingen",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/4f/Humbert_von_Gikkingen.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Green",
            hair_color: "Yellow",
            specie: "Cat",
          },
          {
            id: "079db09e-0441-442b-8c17-af5cac8321c4",
            name: "Seiji Amasawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c5/Seiji_Amasawa.jpg",
            gender: "Male",
            age: "15",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "494bba43-9f61-4383-a597-5bae6ab26222",
            name: "Yuko Harada",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/cb/Yuko_Harada.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "e432a1fe-e937-4575-bade-d11e9f8a9433",
            name: "Sugimura",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b7/Sugimura.jpg",
            gender: "Male",
            age: "14",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "182c1f2a-e1e0-4035-b87a-754d58ed6e2d",
            name: "Seiya Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b3/Seiya_Tsukishima.jpg",
            gender: "Male",
            age: "40",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "d92e61f3-f525-4740-9f06-c9e7b19c3d11",
            name: "Asako Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/ac/Asako_Tsukishima.jpg",
            gender: "Female",
            age: "39",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "61b51987-dd67-479b-aa03-554834b7edd7",
            name: "Shiro Nishi",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Shiro_Nishi.jpg",
            gender: "Male",
            age: "70",
            eye_color: "Black",
            hair_color: "White",
            specie: "Human",
          },
          {
            id: "e40b4241-612b-402f-8e6c-067c44e9c618",
            name: "Shiho Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/02/Shiho_Tsukishima.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "42f787d8-1fcb-4d3d-82f2-a74409869368",
            name: "Seiji's House",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a7/Mimi011.jpg",
            climate: "Continental",
            terrain: "City",
            surface_water: "0",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "2de9426b-914a-4a06-a3a0-5e6d9d3886f6",
        title: "The Secret World of Arrietty",
        description:
          "14-year-old Arrietty and the rest of the Clock family live in peaceful anonymity as they make their own home from items 'borrowed' from the house's human inhabitants. However, life changes for the Clocks when a human boy discovers Arrietty.",
        director: "Hiromasa Yonebayashi",
        producer: "Toshio Suzuki",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZDY3ZGI0ZDAtMThlNy00MzAxLTg4YjAtNjkwYTkxNmQ4MjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        release_date: "2010",
        rt_score: "95",
        people: [
          {
            id: "89026b3a-abc4-4053-ab1a-c6d2eea68faa",
            name: "Karigurashi/Arrietty",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/04/Arrietty.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Auburn",
            specie: "Borrower",
          },
          {
            id: "496031cc-f6af-4f48-b9d1-27f34cb18e10",
            name: "Sho (Shawn)",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/04/Sho.jpg",
            gender: "Male",
            age: "12-14",
            eye_color: "Brown",
            hair_color: "Navy blue/black",
            specie: "Human",
          },
          {
            id: "ef5ee7c5-ae68-418d-a319-f3e79262cd87",
            name: "Homily Clock",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/28/Homily_Clock.jpg",
            gender: "Female",
            age: "52",
            eye_color: "Brown",
            hair_color: "Navy black",
            specie: "Borrower",
          },
          {
            id: "3a83aa65-d134-4e58-85b2-e9f6523b047d",
            name: "Sadako Maki/Jessica",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1b/Jessica.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Black",
            hair_color: "Grey",
            specie: "Human",
          },
          {
            id: "9c687441-3eb3-4c4b-8752-55774953aa3f",
            name: "Haru",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3d/Haru_%28dam%29.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "ce5fb645-f0bb-4c1b-829f-907989d5525f",
            name: "Spiller",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/43/Spiller.jpg",
            gender: "Male",
            age: "Young",
            eye_color: "Black",
            hair_color: "Navy black",
            specie: "Borrower",
          },
          {
            id: "a27ebdcb-4d29-40ac-8da6-5fc5a7869efb",
            name: "Pod Clock",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/7/76/Pod.png",
            gender: "Male",
            age: "52",
            eye_color: "Grey",
            hair_color: "Brown",
            specie: "Borrower",
          },
          {
            id: "379f1453-38ca-486f-9d8b-f4eddc1e3fd3",
            name: "Niya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/5a/Niya.jpg",
            gender: "Male",
            age: "52",
            eye_color: "White",
            hair_color: "Beige",
            specie: "Cat",
          },
        ],
        locations: [
          {
            id: "1e7ed524-4b4f-466b-978c-69dda9777396",
            name: "Sho's house",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/8/86/Karigurashi002.jpg",
            climate: "Warm",
            terrain: "Forest",
            surface_water: "10",
            residents: ["TODO"],
          },
          {
            id: "f2148ab5-f272-4057-b05a-1321e35227b4",
            name: "Karigurashi's house",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/cd/Karigurashi019.jpg",
            climate: "Warm",
            terrain: "Under the floorboards",
            surface_water: "10",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
    ];
    expect(filterByGender(fakeData, "gender", "Female")).toEqual(dataResults);
  });
  it("la data se filtra según el valor elegido por el usuario (Masculino)", () => {
    const dataResults = [
      {
        id: "90b72513-afd4-4570-84de-a56c312fdf81",
        title: "The Cat Returns",
        description:
          "Haru, a schoolgirl bored by her ordinary routine, saves the life of an unusual cat and suddenly her world is transformed beyond anything she ever imagined. The Cat King rewards her good deed with a flurry of presents, including a very shocking proposal of marriage to his son! Haru embarks on an unexpected journey to the Kingdom of Cats where her eyes are opened to a whole other world.",
        director: "Hiroyuki Morita",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/8/87/The_Cat_Returns.jpg",
        release_date: "2002",
        rt_score: "89",
        people: [
          {
            id: "6b3facea-ea33-47b1-96ce-3fc737b119b8",
            name: "Renaldo Moon aka Moon aka Muta",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e7/Muta.png",
            gender: "Male",
            age: "NA",
            eye_color: "White",
            hair_color: "Beige",
            specie: "Cat",
          },
          {
            id: "3042818d-a8bb-4cba-8180-c19249822d57",
            name: "Cat King",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/34/The_Cat_King.jpg",
            gender: "Male",
            age: "87",
            eye_color: "Emerald",
            hair_color: "Grey",
            specie: "Cat",
          },
          {
            id: "58d1973f-f247-47d7-9358-e56cb0d2b5a6",
            name: "Yuki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/eb/New_queen%2C_Yuki.JPG",
            gender: "Female",
            age: "NA",
            eye_color: "Blue",
            hair_color: "White",
            specie: "Cat",
          },
          {
            id: "a3d8e70f-46a0-4e5a-b850-db01620d6b92",
            name: "Haru Yoshioka",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/27/Haru_Yoshioka.jpg",
            gender: "Female",
            age: "17",
            eye_color: "Brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "466bc926-2024-4653-ac63-fe52f2dc8c7b",
            name: "Natori",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c4/Natori.jpg",
            gender: "Male",
            age: "NA",
            eye_color: "Blue",
            hair_color: "Grey",
            specie: "Cat",
          },
          {
            id: "269dcd81-8037-45bb-892b-1c86c9696222",
            name: "Toto",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/8/8d/Toto.png",
            gender: "Male",
            age: "NA",
            eye_color: "Black",
            hair_color: "Dark Blue",
            specie: "Bird",
          },
          {
            id: "5b2a28f6-91d4-4382-aedc-b27094e763b0",
            name: "Prince Lune",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/9/90/Prince_Lune.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Russian blue",
            specie: "Cat",
          },
          {
            id: "17aca709-3049-48fc-95a6-e802c01125a2",
            name: "Hiromi",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c1/Hiromi.png",
            gender: "Female",
            age: "17",
            eye_color: "Brown",
            hair_color: "Light brown",
            specie: "Human",
          },
          {
            id: "911d38e2-ada4-4481-89a2-ba414422d4e4",
            name: "Naoko Yoshioka",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/64/Naoko_Yoshioka.jpg",
            gender: "Female",
            age: "Adult",
            eye_color: "Light Brown",
            hair_color: "Light brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "a8bd9c03-7c80-4a97-b7c0-6a668acaf576",
            name: "The Cat Kingdom",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a9/Baron022.jpg",
            climate: "Continental",
            terrain: "Plain",
            surface_water: "30",
            residents: [
              {
                id: "6b3facea-ea33-47b1-96ce-3fc737b119b8",
                name: "Renaldo Moon aka Moon aka Muta",
              },
              {
                id: "3042818d-a8bb-4cba-8180-c19249822d57",
                name: "Cat King",
              },
              {
                id: "58d1973f-f247-47d7-9358-e56cb0d2b5a6",
                name: "Yuki",
              },
              {
                id: "a3d8e70f-46a0-4e5a-b850-db01620d6b92",
                name: "Haru",
              },
            ],
          },
        ],
        vehicles: [],
      },
      {
        id: "112c1e67-726f-40b1-ac17-6974127bb9b9",
        title: "Tales from Earthsea",
        description:
          "Something bizarre has come over the land. The kingdom is deteriorating. People are beginning to act strange... What's even more strange is that people are beginning to see dragons, which shouldn't enter the world of humans. Due to all these bizarre events, Ged, a wandering wizard, is investigating the cause. During his journey, he meets Prince Arren, a young distraught teenage boy. While Arren may look like a shy young teen, he has a severe dark side, which grants him strength, hatred, ruthlessness and has no mercy, especially when it comes to protecting Teru. For the witch Kumo this is a perfect opportunity. She can use the boy's 'fears' against the very one who would help him, Ged.",
        director: "Gorō Miyazaki",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/0/09/%C3%96v%C3%A4rlden.jpg",
        release_date: "2006",
        rt_score: "41",
        people: [
          {
            id: "68df798d-f73d-4c70-b4ad-05dd84910436",
            name: "Ged",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/33/Ged.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Brown",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "3f3163bb-e2da-4e87-a1bf-ae2dfcde1a09",
            name: "Arren / Lebannen",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/ee/Arren.png",
            gender: "Male",
            age: "17",
            eye_color: "Dark brown",
            hair_color: "Dark brown",
            specie: "Human",
          },
          {
            id: "84ba6d3d-d225-4a92-bbbc-147808826425",
            name: "Therru",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1a/Therru.jpg",
            gender: "Female",
            age: "circa 14-17",
            eye_color: "Dark brown",
            hair_color: "Dark brown",
            specie: "Human",
          },
          {
            id: "60469915-e18e-4cf3-b43d-95ea56cc300c",
            name: "Tenar",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/4f/Tenar.jpg",
            gender: "Female",
            age: "Adult",
            eye_color: "Grey",
            hair_color: "Blonde",
            specie: "Human",
          },
          {
            id: "9bd3091a-8ae2-4741-9265-7f83ec55663a",
            name: "King of Enlad",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/ec/King-enlad.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "59d22f97-f45d-4a6c-b473-13ee9e69082a",
            name: "Cob",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/ce/Cob.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Violet",
            hair_color: "Purple",
            specie: "Arch-mage/Human",
          },
          {
            id: "da00cee4-90a2-413b-8cef-c65e57f7e41",
            name: "Hare",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1e/Hare.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "e024d74b-ca9f-49a7-92fb-e8723c6183e4",
            name: "Hazia Dealer",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1b/Hazia_Dealer.png",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "bcc54f38-8847-45b0-97b1-307c94b2b517",
            name: "Enland",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0e/Ged007.jpg",
            climate: "Wet",
            terrain: "Earthsea",
            surface_water: "100",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "12cfb892-aac0-4c5b-94af-521852e46d6a",
        title: "Grave of the Fireflies",
        description:
          "In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.",
        director: "Isao Takahata",
        producer: "Toru Hara",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg",
        release_date: "1988",
        rt_score: "97",
        people: [
          {
            id: "8cb959a8-1959-42f3-bb33-07d7a2e6b830",
            name: "Seita Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/21/Seita_Yokokawa.jpg",
            gender: "Male",
            age: "14",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "c344d561-6654-4aab-b0df-a1570e7e60cb",
            name: "Setsuko Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a8/Setsuko_Yokokawa.jpg",
            gender: "Female",
            age: "4",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "227c01a6-4e29-4582-bc4b-35106a704ab0",
            name: "Mrs. Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/39/SeitaMother.png",
            gender: "Female",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "023306e3-9fc6-4d1d-b681-d4649dcbfff9",
            name: "Kiyoshi Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/f/f6/SeitaFather3.jpg",
            gender: "Male",
            age: "40",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "0e18b23d-1f21-4a83-a6de-f01147624875",
            name: "Seita's Aunt",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/09/SeitaAunt.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [],
        vehicles: [],
      },
    ];
    expect(filterByGender(fakeData, "gender", "Male")).toEqual(dataResults);
  });
});

describe("sortData", () => {
  it("la data se ordena según el valor elegido por el usuario (ascendente)", () => {
    const dataResults = [
      {
        id: "112c1e67-726f-40b1-ac17-6974127bb9b9",
        title: "Tales from Earthsea",
        description:
          "Something bizarre has come over the land. The kingdom is deteriorating. People are beginning to act strange... What's even more strange is that people are beginning to see dragons, which shouldn't enter the world of humans. Due to all these bizarre events, Ged, a wandering wizard, is investigating the cause. During his journey, he meets Prince Arren, a young distraught teenage boy. While Arren may look like a shy young teen, he has a severe dark side, which grants him strength, hatred, ruthlessness and has no mercy, especially when it comes to protecting Teru. For the witch Kumo this is a perfect opportunity. She can use the boy's 'fears' against the very one who would help him, Ged.",
        director: "Gorō Miyazaki",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/0/09/%C3%96v%C3%A4rlden.jpg",
        release_date: "2006",
        rt_score: "41",
        people: [
          {
            id: "68df798d-f73d-4c70-b4ad-05dd84910436",
            name: "Ged",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/33/Ged.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Brown",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "3f3163bb-e2da-4e87-a1bf-ae2dfcde1a09",
            name: "Arren / Lebannen",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/ee/Arren.png",
            gender: "Male",
            age: "17",
            eye_color: "Dark brown",
            hair_color: "Dark brown",
            specie: "Human",
          },
          {
            id: "84ba6d3d-d225-4a92-bbbc-147808826425",
            name: "Therru",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1a/Therru.jpg",
            gender: "Female",
            age: "circa 14-17",
            eye_color: "Dark brown",
            hair_color: "Dark brown",
            specie: "Human",
          },
          {
            id: "60469915-e18e-4cf3-b43d-95ea56cc300c",
            name: "Tenar",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/4f/Tenar.jpg",
            gender: "Female",
            age: "Adult",
            eye_color: "Grey",
            hair_color: "Blonde",
            specie: "Human",
          },
          {
            id: "9bd3091a-8ae2-4741-9265-7f83ec55663a",
            name: "King of Enlad",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/ec/King-enlad.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "59d22f97-f45d-4a6c-b473-13ee9e69082a",
            name: "Cob",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/ce/Cob.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Violet",
            hair_color: "Purple",
            specie: "Arch-mage/Human",
          },
          {
            id: "da00cee4-90a2-413b-8cef-c65e57f7e41",
            name: "Hare",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1e/Hare.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "e024d74b-ca9f-49a7-92fb-e8723c6183e4",
            name: "Hazia Dealer",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1b/Hazia_Dealer.png",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "bcc54f38-8847-45b0-97b1-307c94b2b517",
            name: "Enland",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0e/Ged007.jpg",
            climate: "Wet",
            terrain: "Earthsea",
            surface_water: "100",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "90b72513-afd4-4570-84de-a56c312fdf81",
        title: "The Cat Returns",
        description:
          "Haru, a schoolgirl bored by her ordinary routine, saves the life of an unusual cat and suddenly her world is transformed beyond anything she ever imagined. The Cat King rewards her good deed with a flurry of presents, including a very shocking proposal of marriage to his son! Haru embarks on an unexpected journey to the Kingdom of Cats where her eyes are opened to a whole other world.",
        director: "Hiroyuki Morita",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/8/87/The_Cat_Returns.jpg",
        release_date: "2002",
        rt_score: "89",
        people: [
          {
            id: "6b3facea-ea33-47b1-96ce-3fc737b119b8",
            name: "Renaldo Moon aka Moon aka Muta",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e7/Muta.png",
            gender: "Male",
            age: "NA",
            eye_color: "White",
            hair_color: "Beige",
            specie: "Cat",
          },
          {
            id: "3042818d-a8bb-4cba-8180-c19249822d57",
            name: "Cat King",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/34/The_Cat_King.jpg",
            gender: "Male",
            age: "87",
            eye_color: "Emerald",
            hair_color: "Grey",
            specie: "Cat",
          },
          {
            id: "58d1973f-f247-47d7-9358-e56cb0d2b5a6",
            name: "Yuki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/eb/New_queen%2C_Yuki.JPG",
            gender: "Female",
            age: "NA",
            eye_color: "Blue",
            hair_color: "White",
            specie: "Cat",
          },
          {
            id: "a3d8e70f-46a0-4e5a-b850-db01620d6b92",
            name: "Haru Yoshioka",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/27/Haru_Yoshioka.jpg",
            gender: "Female",
            age: "17",
            eye_color: "Brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "466bc926-2024-4653-ac63-fe52f2dc8c7b",
            name: "Natori",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c4/Natori.jpg",
            gender: "Male",
            age: "NA",
            eye_color: "Blue",
            hair_color: "Grey",
            specie: "Cat",
          },
          {
            id: "269dcd81-8037-45bb-892b-1c86c9696222",
            name: "Toto",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/8/8d/Toto.png",
            gender: "Male",
            age: "NA",
            eye_color: "Black",
            hair_color: "Dark Blue",
            specie: "Bird",
          },
          {
            id: "5b2a28f6-91d4-4382-aedc-b27094e763b0",
            name: "Prince Lune",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/9/90/Prince_Lune.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Russian blue",
            specie: "Cat",
          },
          {
            id: "17aca709-3049-48fc-95a6-e802c01125a2",
            name: "Hiromi",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c1/Hiromi.png",
            gender: "Female",
            age: "17",
            eye_color: "Brown",
            hair_color: "Light brown",
            specie: "Human",
          },
          {
            id: "911d38e2-ada4-4481-89a2-ba414422d4e4",
            name: "Naoko Yoshioka",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/64/Naoko_Yoshioka.jpg",
            gender: "Female",
            age: "Adult",
            eye_color: "Light Brown",
            hair_color: "Light brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "a8bd9c03-7c80-4a97-b7c0-6a668acaf576",
            name: "The Cat Kingdom",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a9/Baron022.jpg",
            climate: "Continental",
            terrain: "Plain",
            surface_water: "30",
            residents: [
              {
                id: "6b3facea-ea33-47b1-96ce-3fc737b119b8",
                name: "Renaldo Moon aka Moon aka Muta",
              },
              {
                id: "3042818d-a8bb-4cba-8180-c19249822d57",
                name: "Cat King",
              },
              {
                id: "58d1973f-f247-47d7-9358-e56cb0d2b5a6",
                name: "Yuki",
              },
              {
                id: "a3d8e70f-46a0-4e5a-b850-db01620d6b92",
                name: "Haru",
              },
            ],
          },
        ],
        vehicles: [],
      },
      {
        id: "ff24da26-a969-4f0e-ba1e-a122ead6c6e3",
        title: "Whisper of the Heart",
        description:
          "Shizuku lives a simple life, dominated by her love for stories and writing. One day she notices that all the library books she has have been previously checked out by the same person: 'Seiji Amasawa'. Curious as to who he is, Shizuku meets a boy her age whom she finds infuriating, but discovers to her shock that he is her 'Prince of Books'. As she grows closer to him, she realises that he merely read all those books to bring himself closer to her. The boy Seiji aspires to be a violin maker in Italy, and it is his dreams that make Shizuku realise that she has no clear path for her life. Knowing that her strength lies in writing, she tests her talents by writing a story about Baron, a cat statuette belonging to Seiji's grandfather.",
        director: "Yoshifumi Kondō",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/7/7b/Whisper_of_the_Heart.jpg",
        release_date: "1995",
        rt_score: "91",
        people: [
          {
            id: "42a69bf6-b5e8-42b1-b05a-12c3d05e7c1e",
            name: "Shizuku Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/67/Shizuku_Tsukishima.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Light black",
            specie: "Human",
          },
          {
            id: "fc196c4f-0201-4ed2-9add-c6403f7c4d32",
            name: "Baron Humbert von Gikkingen",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/4f/Humbert_von_Gikkingen.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Green",
            hair_color: "Yellow",
            specie: "Cat",
          },
          {
            id: "079db09e-0441-442b-8c17-af5cac8321c4",
            name: "Seiji Amasawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c5/Seiji_Amasawa.jpg",
            gender: "Male",
            age: "15",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "494bba43-9f61-4383-a597-5bae6ab26222",
            name: "Yuko Harada",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/cb/Yuko_Harada.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "e432a1fe-e937-4575-bade-d11e9f8a9433",
            name: "Sugimura",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b7/Sugimura.jpg",
            gender: "Male",
            age: "14",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "182c1f2a-e1e0-4035-b87a-754d58ed6e2d",
            name: "Seiya Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b3/Seiya_Tsukishima.jpg",
            gender: "Male",
            age: "40",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "d92e61f3-f525-4740-9f06-c9e7b19c3d11",
            name: "Asako Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/ac/Asako_Tsukishima.jpg",
            gender: "Female",
            age: "39",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "61b51987-dd67-479b-aa03-554834b7edd7",
            name: "Shiro Nishi",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Shiro_Nishi.jpg",
            gender: "Male",
            age: "70",
            eye_color: "Black",
            hair_color: "White",
            specie: "Human",
          },
          {
            id: "e40b4241-612b-402f-8e6c-067c44e9c618",
            name: "Shiho Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/02/Shiho_Tsukishima.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "42f787d8-1fcb-4d3d-82f2-a74409869368",
            name: "Seiji's House",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a7/Mimi011.jpg",
            climate: "Continental",
            terrain: "City",
            surface_water: "0",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "2de9426b-914a-4a06-a3a0-5e6d9d3886f6",
        title: "The Secret World of Arrietty",
        description:
          "14-year-old Arrietty and the rest of the Clock family live in peaceful anonymity as they make their own home from items 'borrowed' from the house's human inhabitants. However, life changes for the Clocks when a human boy discovers Arrietty.",
        director: "Hiromasa Yonebayashi",
        producer: "Toshio Suzuki",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZDY3ZGI0ZDAtMThlNy00MzAxLTg4YjAtNjkwYTkxNmQ4MjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        release_date: "2010",
        rt_score: "95",
        people: [
          {
            id: "89026b3a-abc4-4053-ab1a-c6d2eea68faa",
            name: "Karigurashi/Arrietty",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/04/Arrietty.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Auburn",
            specie: "Borrower",
          },
          {
            id: "496031cc-f6af-4f48-b9d1-27f34cb18e10",
            name: "Sho (Shawn)",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/04/Sho.jpg",
            gender: "Male",
            age: "12-14",
            eye_color: "Brown",
            hair_color: "Navy blue/black",
            specie: "Human",
          },
          {
            id: "ef5ee7c5-ae68-418d-a319-f3e79262cd87",
            name: "Homily Clock",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/28/Homily_Clock.jpg",
            gender: "Female",
            age: "52",
            eye_color: "Brown",
            hair_color: "Navy black",
            specie: "Borrower",
          },
          {
            id: "3a83aa65-d134-4e58-85b2-e9f6523b047d",
            name: "Sadako Maki/Jessica",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1b/Jessica.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Black",
            hair_color: "Grey",
            specie: "Human",
          },
          {
            id: "9c687441-3eb3-4c4b-8752-55774953aa3f",
            name: "Haru",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3d/Haru_%28dam%29.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "ce5fb645-f0bb-4c1b-829f-907989d5525f",
            name: "Spiller",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/43/Spiller.jpg",
            gender: "Male",
            age: "Young",
            eye_color: "Black",
            hair_color: "Navy black",
            specie: "Borrower",
          },
          {
            id: "a27ebdcb-4d29-40ac-8da6-5fc5a7869efb",
            name: "Pod Clock",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/7/76/Pod.png",
            gender: "Male",
            age: "52",
            eye_color: "Grey",
            hair_color: "Brown",
            specie: "Borrower",
          },
          {
            id: "379f1453-38ca-486f-9d8b-f4eddc1e3fd3",
            name: "Niya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/5a/Niya.jpg",
            gender: "Male",
            age: "52",
            eye_color: "White",
            hair_color: "Beige",
            specie: "Cat",
          },
        ],
        locations: [
          {
            id: "1e7ed524-4b4f-466b-978c-69dda9777396",
            name: "Sho's house",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/8/86/Karigurashi002.jpg",
            climate: "Warm",
            terrain: "Forest",
            surface_water: "10",
            residents: ["TODO"],
          },
          {
            id: "f2148ab5-f272-4057-b05a-1321e35227b4",
            name: "Karigurashi's house",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/cd/Karigurashi019.jpg",
            climate: "Warm",
            terrain: "Under the floorboards",
            surface_water: "10",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "ea660b10-85c4-4ae3-8a5f-41cea3648e3e",
        title: "Kiki's Delivery Service",
        description:
          "A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.",
        director: "Hayao Miyazaki",
        producer: "Hayao Miyazaki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/4/48/Kiki%27s_Delivery_Service_%282%29.jpg",
        release_date: "1989",
        rt_score: "96",
        people: [
          {
            id: "4151abc6-1a9e-4e6a-5678-aac05ra641js",
            name: "Kiki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/59/Kiki.jpg",
            gender: "Female",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Witch",
          },
          {
            id: "7151abc6-1a9e-4e6a-9711-ddb50ea572ec",
            name: "Jiji",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b4/Jiji.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Cat",
          },
          {
            id: "6574cfr2-9w3d-2x1h-8531-gge23iu489ko",
            name: "Ursula",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/12/Ursula.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "4321dse3-6r6s-3r4d-5641-rdq19re765de",
            name: "Tombo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/6f/Tombo.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
            name: "Osono",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3a/Osono.jpg",
            gender: "Female",
            age: "30",
            eye_color: "Brown",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
            name: "Fukuo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Fukuo.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "fb083a4e-77b2-4623-a2e0-6bbca5bfd5b2",
            name: "Ursula's Log Cabin",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b5/Ursula%27s_Log_Cabin.jpg",
            climate: "TODO",
            terrain: "TODO",
            surface_water: "40",
            residents: ["TODO"],
          },
          {
            id: "c57fb2cb-ea85-4d73-8808-cf5dcd28c22e",
            name: "Koriko",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/05/Koriko.jpg",
            climate: "Mild",
            terrain: "Hill",
            surface_water: "50",
            residents: ["TODO"],
          },
          {
            id: "62346d33-caa0-4c17-8016-0aca56f3066b",
            name: "Karikiya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e3/Majo002.jpg",
            climate: "Mild",
            terrain: "City",
            surface_water: "30",
            residents: ["TODO"],
          },
          {
            id: "64a996aa-481e-4627-9624-ab23f59a05a9",
            name: "Guchokipanya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Gutiokipanja.jpg",
            climate: "Continental",
            terrain: "Hill",
            surface_water: "50",
            residents: [
              {
                id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
                name: "Osono",
              },
              {
                id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
                name: "Fukuo",
              },
            ],
          },
        ],
        vehicles: [],
      },
      {
        id: "12cfb892-aac0-4c5b-94af-521852e46d6a",
        title: "Grave of the Fireflies",
        description:
          "In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.",
        director: "Isao Takahata",
        producer: "Toru Hara",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg",
        release_date: "1988",
        rt_score: "97",
        people: [
          {
            id: "8cb959a8-1959-42f3-bb33-07d7a2e6b830",
            name: "Seita Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/21/Seita_Yokokawa.jpg",
            gender: "Male",
            age: "14",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "c344d561-6654-4aab-b0df-a1570e7e60cb",
            name: "Setsuko Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a8/Setsuko_Yokokawa.jpg",
            gender: "Female",
            age: "4",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "227c01a6-4e29-4582-bc4b-35106a704ab0",
            name: "Mrs. Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/39/SeitaMother.png",
            gender: "Female",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "023306e3-9fc6-4d1d-b681-d4649dcbfff9",
            name: "Kiyoshi Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/f/f6/SeitaFather3.jpg",
            gender: "Male",
            age: "40",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "0e18b23d-1f21-4a83-a6de-f01147624875",
            name: "Seita's Aunt",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/09/SeitaAunt.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [],
        vehicles: [],
      },
    ];
    expect(sortData(fakeData, "rt_score", "asc")).toEqual(dataResults);
  });
  it("la data se ordena según el valor elegido por el usuario (descendente)", () => {
    const dataResults = [
      {
        id: "12cfb892-aac0-4c5b-94af-521852e46d6a",
        title: "Grave of the Fireflies",
        description:
          "In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.",
        director: "Isao Takahata",
        producer: "Toru Hara",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/a/a5/Grave_of_the_Fireflies_Japanese_poster.jpg",
        release_date: "1988",
        rt_score: "97",
        people: [
          {
            id: "8cb959a8-1959-42f3-bb33-07d7a2e6b830",
            name: "Seita Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/21/Seita_Yokokawa.jpg",
            gender: "Male",
            age: "14",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "c344d561-6654-4aab-b0df-a1570e7e60cb",
            name: "Setsuko Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a8/Setsuko_Yokokawa.jpg",
            gender: "Female",
            age: "4",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "227c01a6-4e29-4582-bc4b-35106a704ab0",
            name: "Mrs. Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/39/SeitaMother.png",
            gender: "Female",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "023306e3-9fc6-4d1d-b681-d4649dcbfff9",
            name: "Kiyoshi Yokokawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/f/f6/SeitaFather3.jpg",
            gender: "Male",
            age: "40",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "0e18b23d-1f21-4a83-a6de-f01147624875",
            name: "Seita's Aunt",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/09/SeitaAunt.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [],
        vehicles: [],
      },
      {
        id: "ea660b10-85c4-4ae3-8a5f-41cea3648e3e",
        title: "Kiki's Delivery Service",
        description:
          "A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.",
        director: "Hayao Miyazaki",
        producer: "Hayao Miyazaki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/4/48/Kiki%27s_Delivery_Service_%282%29.jpg",
        release_date: "1989",
        rt_score: "96",
        people: [
          {
            id: "4151abc6-1a9e-4e6a-5678-aac05ra641js",
            name: "Kiki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/59/Kiki.jpg",
            gender: "Female",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Witch",
          },
          {
            id: "7151abc6-1a9e-4e6a-9711-ddb50ea572ec",
            name: "Jiji",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b4/Jiji.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Cat",
          },
          {
            id: "6574cfr2-9w3d-2x1h-8531-gge23iu489ko",
            name: "Ursula",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/12/Ursula.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "4321dse3-6r6s-3r4d-5641-rdq19re765de",
            name: "Tombo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/6f/Tombo.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
            name: "Osono",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3a/Osono.jpg",
            gender: "Female",
            age: "30",
            eye_color: "Brown",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
            name: "Fukuo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Fukuo.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "fb083a4e-77b2-4623-a2e0-6bbca5bfd5b2",
            name: "Ursula's Log Cabin",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b5/Ursula%27s_Log_Cabin.jpg",
            climate: "TODO",
            terrain: "TODO",
            surface_water: "40",
            residents: ["TODO"],
          },
          {
            id: "c57fb2cb-ea85-4d73-8808-cf5dcd28c22e",
            name: "Koriko",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/05/Koriko.jpg",
            climate: "Mild",
            terrain: "Hill",
            surface_water: "50",
            residents: ["TODO"],
          },
          {
            id: "62346d33-caa0-4c17-8016-0aca56f3066b",
            name: "Karikiya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e3/Majo002.jpg",
            climate: "Mild",
            terrain: "City",
            surface_water: "30",
            residents: ["TODO"],
          },
          {
            id: "64a996aa-481e-4627-9624-ab23f59a05a9",
            name: "Guchokipanya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Gutiokipanja.jpg",
            climate: "Continental",
            terrain: "Hill",
            surface_water: "50",
            residents: [
              {
                id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
                name: "Osono",
              },
              {
                id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
                name: "Fukuo",
              },
            ],
          },
        ],
        vehicles: [],
      },
      {
        id: "2de9426b-914a-4a06-a3a0-5e6d9d3886f6",
        title: "The Secret World of Arrietty",
        description:
          "14-year-old Arrietty and the rest of the Clock family live in peaceful anonymity as they make their own home from items 'borrowed' from the house's human inhabitants. However, life changes for the Clocks when a human boy discovers Arrietty.",
        director: "Hiromasa Yonebayashi",
        producer: "Toshio Suzuki",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZDY3ZGI0ZDAtMThlNy00MzAxLTg4YjAtNjkwYTkxNmQ4MjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        release_date: "2010",
        rt_score: "95",
        people: [
          {
            id: "89026b3a-abc4-4053-ab1a-c6d2eea68faa",
            name: "Karigurashi/Arrietty",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/04/Arrietty.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Auburn",
            specie: "Borrower",
          },
          {
            id: "496031cc-f6af-4f48-b9d1-27f34cb18e10",
            name: "Sho (Shawn)",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/04/Sho.jpg",
            gender: "Male",
            age: "12-14",
            eye_color: "Brown",
            hair_color: "Navy blue/black",
            specie: "Human",
          },
          {
            id: "ef5ee7c5-ae68-418d-a319-f3e79262cd87",
            name: "Homily Clock",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/28/Homily_Clock.jpg",
            gender: "Female",
            age: "52",
            eye_color: "Brown",
            hair_color: "Navy black",
            specie: "Borrower",
          },
          {
            id: "3a83aa65-d134-4e58-85b2-e9f6523b047d",
            name: "Sadako Maki/Jessica",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1b/Jessica.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Black",
            hair_color: "Grey",
            specie: "Human",
          },
          {
            id: "9c687441-3eb3-4c4b-8752-55774953aa3f",
            name: "Haru",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3d/Haru_%28dam%29.jpg",
            gender: "Female",
            age: "Elder",
            eye_color: "Brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "ce5fb645-f0bb-4c1b-829f-907989d5525f",
            name: "Spiller",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/43/Spiller.jpg",
            gender: "Male",
            age: "Young",
            eye_color: "Black",
            hair_color: "Navy black",
            specie: "Borrower",
          },
          {
            id: "a27ebdcb-4d29-40ac-8da6-5fc5a7869efb",
            name: "Pod Clock",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/7/76/Pod.png",
            gender: "Male",
            age: "52",
            eye_color: "Grey",
            hair_color: "Brown",
            specie: "Borrower",
          },
          {
            id: "379f1453-38ca-486f-9d8b-f4eddc1e3fd3",
            name: "Niya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/5a/Niya.jpg",
            gender: "Male",
            age: "52",
            eye_color: "White",
            hair_color: "Beige",
            specie: "Cat",
          },
        ],
        locations: [
          {
            id: "1e7ed524-4b4f-466b-978c-69dda9777396",
            name: "Sho's house",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/8/86/Karigurashi002.jpg",
            climate: "Warm",
            terrain: "Forest",
            surface_water: "10",
            residents: ["TODO"],
          },
          {
            id: "f2148ab5-f272-4057-b05a-1321e35227b4",
            name: "Karigurashi's house",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/cd/Karigurashi019.jpg",
            climate: "Warm",
            terrain: "Under the floorboards",
            surface_water: "10",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "ff24da26-a969-4f0e-ba1e-a122ead6c6e3",
        title: "Whisper of the Heart",
        description:
          "Shizuku lives a simple life, dominated by her love for stories and writing. One day she notices that all the library books she has have been previously checked out by the same person: 'Seiji Amasawa'. Curious as to who he is, Shizuku meets a boy her age whom she finds infuriating, but discovers to her shock that he is her 'Prince of Books'. As she grows closer to him, she realises that he merely read all those books to bring himself closer to her. The boy Seiji aspires to be a violin maker in Italy, and it is his dreams that make Shizuku realise that she has no clear path for her life. Knowing that her strength lies in writing, she tests her talents by writing a story about Baron, a cat statuette belonging to Seiji's grandfather.",
        director: "Yoshifumi Kondō",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/7/7b/Whisper_of_the_Heart.jpg",
        release_date: "1995",
        rt_score: "91",
        people: [
          {
            id: "42a69bf6-b5e8-42b1-b05a-12c3d05e7c1e",
            name: "Shizuku Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/67/Shizuku_Tsukishima.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Light black",
            specie: "Human",
          },
          {
            id: "fc196c4f-0201-4ed2-9add-c6403f7c4d32",
            name: "Baron Humbert von Gikkingen",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/4f/Humbert_von_Gikkingen.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Green",
            hair_color: "Yellow",
            specie: "Cat",
          },
          {
            id: "079db09e-0441-442b-8c17-af5cac8321c4",
            name: "Seiji Amasawa",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c5/Seiji_Amasawa.jpg",
            gender: "Male",
            age: "15",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "494bba43-9f61-4383-a597-5bae6ab26222",
            name: "Yuko Harada",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/cb/Yuko_Harada.jpg",
            gender: "Female",
            age: "14",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "e432a1fe-e937-4575-bade-d11e9f8a9433",
            name: "Sugimura",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b7/Sugimura.jpg",
            gender: "Male",
            age: "14",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "182c1f2a-e1e0-4035-b87a-754d58ed6e2d",
            name: "Seiya Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b3/Seiya_Tsukishima.jpg",
            gender: "Male",
            age: "40",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "d92e61f3-f525-4740-9f06-c9e7b19c3d11",
            name: "Asako Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/ac/Asako_Tsukishima.jpg",
            gender: "Female",
            age: "39",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "61b51987-dd67-479b-aa03-554834b7edd7",
            name: "Shiro Nishi",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Shiro_Nishi.jpg",
            gender: "Male",
            age: "70",
            eye_color: "Black",
            hair_color: "White",
            specie: "Human",
          },
          {
            id: "e40b4241-612b-402f-8e6c-067c44e9c618",
            name: "Shiho Tsukishima",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/02/Shiho_Tsukishima.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "42f787d8-1fcb-4d3d-82f2-a74409869368",
            name: "Seiji's House",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a7/Mimi011.jpg",
            climate: "Continental",
            terrain: "City",
            surface_water: "0",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
      {
        id: "90b72513-afd4-4570-84de-a56c312fdf81",
        title: "The Cat Returns",
        description:
          "Haru, a schoolgirl bored by her ordinary routine, saves the life of an unusual cat and suddenly her world is transformed beyond anything she ever imagined. The Cat King rewards her good deed with a flurry of presents, including a very shocking proposal of marriage to his son! Haru embarks on an unexpected journey to the Kingdom of Cats where her eyes are opened to a whole other world.",
        director: "Hiroyuki Morita",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/8/87/The_Cat_Returns.jpg",
        release_date: "2002",
        rt_score: "89",
        people: [
          {
            id: "6b3facea-ea33-47b1-96ce-3fc737b119b8",
            name: "Renaldo Moon aka Moon aka Muta",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e7/Muta.png",
            gender: "Male",
            age: "NA",
            eye_color: "White",
            hair_color: "Beige",
            specie: "Cat",
          },
          {
            id: "3042818d-a8bb-4cba-8180-c19249822d57",
            name: "Cat King",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/34/The_Cat_King.jpg",
            gender: "Male",
            age: "87",
            eye_color: "Emerald",
            hair_color: "Grey",
            specie: "Cat",
          },
          {
            id: "58d1973f-f247-47d7-9358-e56cb0d2b5a6",
            name: "Yuki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/eb/New_queen%2C_Yuki.JPG",
            gender: "Female",
            age: "NA",
            eye_color: "Blue",
            hair_color: "White",
            specie: "Cat",
          },
          {
            id: "a3d8e70f-46a0-4e5a-b850-db01620d6b92",
            name: "Haru Yoshioka",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/27/Haru_Yoshioka.jpg",
            gender: "Female",
            age: "17",
            eye_color: "Brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "466bc926-2024-4653-ac63-fe52f2dc8c7b",
            name: "Natori",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c4/Natori.jpg",
            gender: "Male",
            age: "NA",
            eye_color: "Blue",
            hair_color: "Grey",
            specie: "Cat",
          },
          {
            id: "269dcd81-8037-45bb-892b-1c86c9696222",
            name: "Toto",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/8/8d/Toto.png",
            gender: "Male",
            age: "NA",
            eye_color: "Black",
            hair_color: "Dark Blue",
            specie: "Bird",
          },
          {
            id: "5b2a28f6-91d4-4382-aedc-b27094e763b0",
            name: "Prince Lune",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/9/90/Prince_Lune.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Russian blue",
            specie: "Cat",
          },
          {
            id: "17aca709-3049-48fc-95a6-e802c01125a2",
            name: "Hiromi",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/c1/Hiromi.png",
            gender: "Female",
            age: "17",
            eye_color: "Brown",
            hair_color: "Light brown",
            specie: "Human",
          },
          {
            id: "911d38e2-ada4-4481-89a2-ba414422d4e4",
            name: "Naoko Yoshioka",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/64/Naoko_Yoshioka.jpg",
            gender: "Female",
            age: "Adult",
            eye_color: "Light Brown",
            hair_color: "Light brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "a8bd9c03-7c80-4a97-b7c0-6a668acaf576",
            name: "The Cat Kingdom",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/a/a9/Baron022.jpg",
            climate: "Continental",
            terrain: "Plain",
            surface_water: "30",
            residents: [
              {
                id: "6b3facea-ea33-47b1-96ce-3fc737b119b8",
                name: "Renaldo Moon aka Moon aka Muta",
              },
              {
                id: "3042818d-a8bb-4cba-8180-c19249822d57",
                name: "Cat King",
              },
              {
                id: "58d1973f-f247-47d7-9358-e56cb0d2b5a6",
                name: "Yuki",
              },
              {
                id: "a3d8e70f-46a0-4e5a-b850-db01620d6b92",
                name: "Haru",
              },
            ],
          },
        ],
        vehicles: [],
      },
      {
        id: "112c1e67-726f-40b1-ac17-6974127bb9b9",
        title: "Tales from Earthsea",
        description:
          "Something bizarre has come over the land. The kingdom is deteriorating. People are beginning to act strange... What's even more strange is that people are beginning to see dragons, which shouldn't enter the world of humans. Due to all these bizarre events, Ged, a wandering wizard, is investigating the cause. During his journey, he meets Prince Arren, a young distraught teenage boy. While Arren may look like a shy young teen, he has a severe dark side, which grants him strength, hatred, ruthlessness and has no mercy, especially when it comes to protecting Teru. For the witch Kumo this is a perfect opportunity. She can use the boy's 'fears' against the very one who would help him, Ged.",
        director: "Gorō Miyazaki",
        producer: "Toshio Suzuki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/0/09/%C3%96v%C3%A4rlden.jpg",
        release_date: "2006",
        rt_score: "41",
        people: [
          {
            id: "68df798d-f73d-4c70-b4ad-05dd84910436",
            name: "Ged",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/33/Ged.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Brown",
            hair_color: "Black",
            specie: "Human",
          },
          {
            id: "3f3163bb-e2da-4e87-a1bf-ae2dfcde1a09",
            name: "Arren / Lebannen",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/ee/Arren.png",
            gender: "Male",
            age: "17",
            eye_color: "Dark brown",
            hair_color: "Dark brown",
            specie: "Human",
          },
          {
            id: "84ba6d3d-d225-4a92-bbbc-147808826425",
            name: "Therru",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1a/Therru.jpg",
            gender: "Female",
            age: "circa 14-17",
            eye_color: "Dark brown",
            hair_color: "Dark brown",
            specie: "Human",
          },
          {
            id: "60469915-e18e-4cf3-b43d-95ea56cc300c",
            name: "Tenar",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/4/4f/Tenar.jpg",
            gender: "Female",
            age: "Adult",
            eye_color: "Grey",
            hair_color: "Blonde",
            specie: "Human",
          },
          {
            id: "9bd3091a-8ae2-4741-9265-7f83ec55663a",
            name: "King of Enlad",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/ec/King-enlad.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "59d22f97-f45d-4a6c-b473-13ee9e69082a",
            name: "Cob",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/c/ce/Cob.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Violet",
            hair_color: "Purple",
            specie: "Arch-mage/Human",
          },
          {
            id: "da00cee4-90a2-413b-8cef-c65e57f7e41",
            name: "Hare",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1e/Hare.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "e024d74b-ca9f-49a7-92fb-e8723c6183e4",
            name: "Hazia Dealer",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/1b/Hazia_Dealer.png",
            gender: "Male",
            age: "Adult",
            eye_color: "Dark brown",
            hair_color: "Brown",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "bcc54f38-8847-45b0-97b1-307c94b2b517",
            name: "Enland",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0e/Ged007.jpg",
            climate: "Wet",
            terrain: "Earthsea",
            surface_water: "100",
            residents: ["TODO"],
          },
        ],
        vehicles: [],
      },
    ];
    expect(sortData(fakeData, "rt_score", "desc")).toEqual(dataResults);
  });
});

describe("computeStats", () => {
  it("la función devuelve un porcentaje de personajes de especie no-humana", () => {
    const simulatedData = [
      {
        id: "ea660b10-85c4-4ae3-8a5f-41cea3648e3e",
        title: "Kiki's Delivery Service",
        description:
          "A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.",
        director: "Hayao Miyazaki",
        producer: "Hayao Miyazaki",
        poster:
          "https://static.wikia.nocookie.net/studio-ghibli/images/4/48/Kiki%27s_Delivery_Service_%282%29.jpg",
        release_date: "1989",
        rt_score: "96",
        people: [
          {
            id: "4151abc6-1a9e-4e6a-5678-aac05ra641js",
            name: "Kiki",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/5/59/Kiki.jpg",
            gender: "Female",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Witch",
          },
          {
            id: "7151abc6-1a9e-4e6a-9711-ddb50ea572ec",
            name: "Jiji",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b4/Jiji.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Cat",
          },
          {
            id: "6574cfr2-9w3d-2x1h-8531-gge23iu489ko",
            name: "Ursula",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/1/12/Ursula.jpg",
            gender: "Female",
            age: "18",
            eye_color: "Black",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "4321dse3-6r6s-3r4d-5641-rdq19re765de",
            name: "Tombo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/6/6f/Tombo.jpg",
            gender: "Male",
            age: "13",
            eye_color: "Black",
            hair_color: "Brown",
            specie: "Human",
          },
          {
            id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
            name: "Osono",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/3/3a/Osono.jpg",
            gender: "Female",
            age: "30",
            eye_color: "Brown",
            hair_color: "Red",
            specie: "Human",
          },
          {
            id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
            name: "Fukuo",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/2/29/Fukuo.jpg",
            gender: "Male",
            age: "Adult",
            eye_color: "Black",
            hair_color: "Black",
            specie: "Human",
          },
        ],
        locations: [
          {
            id: "fb083a4e-77b2-4623-a2e0-6bbca5bfd5b2",
            name: "Ursula's Log Cabin",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b5/Ursula%27s_Log_Cabin.jpg",
            climate: "TODO",
            terrain: "TODO",
            surface_water: "40",
            residents: ["TODO"],
          },
          {
            id: "c57fb2cb-ea85-4d73-8808-cf5dcd28c22e",
            name: "Koriko",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/05/Koriko.jpg",
            climate: "Mild",
            terrain: "Hill",
            surface_water: "50",
            residents: ["TODO"],
          },
          {
            id: "62346d33-caa0-4c17-8016-0aca56f3066b",
            name: "Karikiya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/e/e3/Majo002.jpg",
            climate: "Mild",
            terrain: "City",
            surface_water: "30",
            residents: ["TODO"],
          },
          {
            id: "64a996aa-481e-4627-9624-ab23f59a05a9",
            name: "Guchokipanya",
            img: "https://static.wikia.nocookie.net/studio-ghibli/images/0/0f/Gutiokipanja.jpg",
            climate: "Continental",
            terrain: "Hill",
            surface_water: "50",
            residents: [
              {
                id: "8252ebf6-1g8f-5t6u-1234-vvg45yd363dc",
                name: "Osono",
              },
              {
                id: "7654ght4-3r4t-1t5u-0987-hhj76gh432gr",
                name: "Fukuo",
              },
            ],
          },
        ],
        vehicles: [],
      },
    ];
    const percentageResults = computeStats(simulatedData);
    expect(computeStats(simulatedData)).toEqual(percentageResults);
  });
});
